global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nvidia'
    static_configs:
      - targets: ['dcgm-exporter:9400']


  - job_name: 'vllm'
    scrape_interval: 2m
    scrape_timeout: 30s
    scheme: https
    tls_config:
      insecure_skip_verify: false
    static_configs:
      - targets: ['thinking.quanghung20gg.site']

      


