name: Deploy and Restart API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          echo -e "Host quanghung\n  HostName ${{ secrets.SERVER_HOST }}\n  User ${{ secrets.SERVER_USER }}\n  ProxyCommand cloudflared access ssh --hostname %h\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Install Cloudflare Tunnel
        run: |
          sudo apt update
          sudo mkdir -p /usr/local/bin
          sudo curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared
          sudo chmod +x /usr/local/bin/cloudflared
          cloudflared --version

      - name: Reload API
        run: |
          ssh quanghung << 'EOF'
            cd ~/Documents/new/neu_solution/training_cluster
            git pull origin main
            cd ~/Documents/new/neu_solution/training_cluster/api
            source ~/anaconda3/etc/profile.d/conda.sh
            conda activate evaluate
            pkill -f 'uvicorn.*23478' || true
            sleep 2
            nohup uvicorn train_server:app --host 0.0.0.0 --port 23478 --reload > uvicorn.log 2>&1 &
            exit
          EOF
            
